spring.datasource.url=jdbc:postgresql://komodo-database.ctttyupfnwik.us-east-1.rds.amazonaws.com:5432/postgres?useSSL=false
spring.datasource.name=postgres
spring.datasource.username=kjistik
spring.datasource.password=332018tgmc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.sql.init.continue-on-error=false
spring.datasource.initialization-mode=always
